when: 
  - event: [push,tag]
    branch: master

steps:
  - name: build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: sylviamic/python_lung_morphometrics
      auto_tag: true
      #tags: latest
      username:
        from_secret: dockerhub_auth_username
      password:
        from_secret: dockerhub_auth_token