when: 
  - event: [push]
    branch: master

steps:
  - name: build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: sylviamic/python_lung_morphometrics
      tags: latest
      username:
        from_secret: dockerhub_auth_username
      password:
        from_secret: dockerhub_auth_token
  - name: test
    image: sylviamic/python_lung_morphometrics:latest
    commands:
      - echo "Testing ..."
      - cd /python_lung_morphometrics && make test