when:
  - event: tag
    branch: master

steps:
  - name: package
    image: sylviamic/python_lung_morphometrics
    environment:
      PYPI_API_KEY: 
        from_secret: pypi_api_key
    commands:
      - echo "Packaging..."
      - cd python_lung_morphometrics
      - make dist
      - python -m twine upload --username __token__ --password $PYPI_API_KEY --repository pypi --verbose dist/*